# FOR DEVELOPMENT ONLY
# See README.md for an example

version: '3.8'

services:
  sync:
    image: cupcakearmy/gitea-sync
    build: .
    env_file: .env

  server:
    image: gitea/gitea:1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
